class Solution {
public:
    int removeDuplicates(vector<int>& nums) {
        // Special case...
        if(nums.size() <= 2) {
            return nums.size();
        }
        // Initialize an integer k that updates the kth index of the array...
        // only when the current element does not match either of the two previous indexes...
        int k = 2;
        // Traverse elements through loop...
        for(int i = 2; i < nums.size(); i++){
            // If the index does not match the (k-1)th and (k-2)th elements, count that element...
            if(nums[i] != nums[k - 2] || nums[i] != nums[k - 1]){
                nums[k] = nums[i];
                k++;
            // If the index matches the (k-1)th and (k-2)th elements, we skip it...
            }
        }
        return k;       //Return k after placing the final result in the first k slots of nums...
    }
};